export const EVENT_CATALOG = [
  "page_view",
  "hero_view",
  "section_view",
  "scroll_25",
  "scroll_50",
  "scroll_75",
  "scroll_100",
  "cta_click",
  "whatsapp_click",
  "email_click",
  "phone_click",
  "form_view",
  "form_start",
  "form_submit",
  "exit_page",
  "heatmap_click",
  "heatmap_scroll",
  "login",
  "logout",
  "signup",
  "email_confirmed",
  "password_recovery",
  "profile_updated",
  "company_doc_uploaded",
  "project_created",
  "project_updated",
  "project_doc_uploaded",
  "project_photo_uploaded",
  "project_submitted",
  "project_resubmitted",
  "curation_started",
  "curation_adjustment",
  "curation_rejected",
  "curation_approved",
  "offer_published",
  "api_error",
  "replay_chunk",
] as const;

export type AnalyticsEventName = (typeof EVENT_CATALOG)[number];

export const FUNNEL_STEPS: readonly AnalyticsEventName[] = [
  "page_view",
  "hero_view",
  "section_view",
  "form_view",
  "form_start",
  "form_submit",
  "email_confirmed",
  "login",
  "profile_updated",
  "project_created",
  "project_submitted",
  "offer_published",
] as const;

export const FUNNEL_STEP_LABELS: Record<string, string> = {
  page_view: "Visitante LP",
  hero_view: "Visualizou Hero",
  section_view: "Seção chave",
  form_view: "Viu formulário",
  form_start: "Iniciou formulário",
  form_submit: "Enviou cadastro",
  email_confirmed: "Confirmou e-mail",
  login: "Primeiro login",
  profile_updated: "Completou perfil",
  project_created: "Criou projeto",
  project_submitted: "Submeteu curadoria",
  offer_published: "Oferta publicada",
};
