import {
  INCORPORADORAS_TABLE,
  ADMINS_TABLE,
  PROJETOS_TABLE,
  SCORECARD_TABLE,
  NOTIFICACOES_TABLE,
  AUDITORIA_TABLE,
  NOTAS_TABLE,
} from './env.js';

/** Centralizes all DynamoDB table name references. */
export const Tables = {
  INCORPORADORAS: INCORPORADORAS_TABLE,
  ADMINS: ADMINS_TABLE,
  PROJETOS: PROJETOS_TABLE,
  SCORECARD: SCORECARD_TABLE,
  NOTIFICACOES: NOTIFICACOES_TABLE,
  AUDITORIA: AUDITORIA_TABLE,
  NOTAS: NOTAS_TABLE,
} as const;
